insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'ALIM', 'Alimentos', 'Optimized composite encryption');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'CUIDP', 'Cuidado Personal', 'Enterprise-wide content-based matrices');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'DEPO', 'Deportes', 'Innovative object-oriented extranet');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'ELEC', 'Electronicos', 'Compatible upward-trending task-force');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'HERR', 'Herramientas', 'Universal systematic application');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'HOG', 'Hogar', 'Focused encompassing toolset');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'MUSIC', 'Instrumentos musicales', 'Visionary impactful capability');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'LIBS', 'Libros', 'Proactive local parallelism');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'OFIC', 'Oficina y papeleria', 'Ergonomic zero tolerance website');
insert into tipo_paquete (id_tipo_paquete, clave, descripcion, indicaciones_generales) values (tipo_paquete_seq.nextval, 'OTROS', 'Otros', 'Persistent coherent portal');
